tcf_website/static/common/sorting.js

Done, In progress, etc
Changed the common sorting script to sort reviews/classes using numerical comparison rather than string comparison (35 > 2). Very simple two-line change to parse as a float after regex.
#189 
N/A but can go to any course/review page to sort

fixed sorting by text comparison instead of numerical

---

tcf_website/templates/course/course.html
tcf_website/views/browse.py

Done
- added `semester_last_taught` to "old" professors
- refactored a Django view (`course_view`) to reduce unnecessary database access
- changed `course.html` accordingly
This fixes #243 and supercedes #218.
As you can see, the performance difference between and after the refactoring is dramatic. Note that the requests in the red box do not even include `semester_last_taught` for "old" professors, while the requests in the green box do.

Refactor and improve the speed of /course/{course_id}

---

tcf_core/settings.py

Done
- Redirected all HTTP requests to HTTPS by adding a single line in `settings.py`
- We only need to write HTTPS URLs on Google Developer Console (effectively preventing issues like [this](https://discord.com/channels/752270432329269328/764555745806647317/767068336852566046))
- Closes #285

Force-redirect to HTTPS on Heroku

---

tcf_website/api/serializers.py
tcf_website/static/department/loadMoreCourses.js

Done
- Change how `season` is cased in the API. 
- Note that other APIs are also affected because `SemesterSerializer` is often nested in another serializer.
Before:
After:

Fix semester casing in write-review page

---

tcf_website/templates/landing/landing.html
tcf_website/templates/reviews/new_review.html

Done
- Linked landing page review button to page
- Frontend review textinput validation
- 100 char min length + 5000 char max length
- Cases: 
- length < 100: Can't submit (prompt shown)
- length > 5000: Not possible, text box won't let you type anymore
- length == 0: Submits successfully (input not required) 
- Have review show up when it redirects to my review page
- Couldn't reproduce this issue locally? When I review successfully it shows on the My Reviews page.
Frontend review textinput validation (min length)

Review page fixes

---

tcf_website/tests/test_review.py
tcf_website/views/review.py

- Done
- This PR closes #357 
- Inspected code that adds message for newly created reviews in `views.new_review`
- Added override for generic `DeleteReview`'s `delete()` method. The override adds a message to the request, then invokes superclass `delete()` so that the review is properly deleted
- Before: deleting a review leaves no message or confirmation
- After: deleting a review leaves a banner-style message confirming successful deletion
Steps to test:
1. Create a new review
2. From the reviews page, delete your newly created review
3. Observe a message indicating your review has been deleted
- It would probably be most idiomatic to use [SuccessMessageMixin](https://docs.djangoproject.com/en/3.1/ref/contrib/messages/#django.contrib.messages.views.SuccessMessageMixin) from Django. I …

Add 'deleted review' message on reviews page

---

.github/workflows/master-to-app-engine.yml
scripts/notify-deployment-result.sh

- Done
- This PR closes #387
- Send a Discord notification when deployment is finished.
- Before: None
- After: Depending on the result of the deployment, there will be two kinds of messages:
- If you want to test it, assign the following variables at the top of the shell script:
```bash
GITHUB_RUN_ID="something"  # Click one from https://github.com/thecourseforum/theCourseForum2/actions if you want a legit link
DEPLOY_RESULT="success"  # or any other string if you want to test the failure case
DISCORD_WEBHOOK=""  # On our Discord server, go to #builds, click on `Edit Channel` - `Integrations` - `View Webhooks` - `GitHub Actions Bot` -` Copy Webhook URL`
```
- We'll actually test this on production on the first Sunday of March.
- Should the commit history be …

Add discord notification for deployment

---

tcf_core/settings/__init__.py

- Done
- This PR closes #411.
- Moved silk-related code inside an `if` statement so that it doesn't get executed on Heroku or GAE.
| Before | After |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/7676354/109427364-16e94480-79c0-11eb-8a1b-d89b1418c5c5.png) | ![image](https://user-images.githubusercontent.com/7676354/109427475-a0007b80-79c0-11eb-9f78-0215bba8da57.png) |
1. Run `docker exec -ti tcf_db psql tcf_db -U tcf_django` and then run `\dt` inside the PostgreSQL shell to verify that silk-related tables are there, just like in the screenshot.
2. Change the `if` statement to `if False:`
3. Run `docker exec -ti tcf_db psql tcf_db -U tcf_django` and then run `\dt` inside the PostgreSQL shell to verify that silk-related tables are gone. From this, we see that the `if` …

Disable django-silk on Heroku/GAE

---

.github/pull_request_template.md

- Done
- This PR closes 
- Changed the PR template to include a message telling people to add their changes to the [release history page](https://github.com/thecourseforum/theCourseForum2/wiki/Release-History) on the wiki. This is so exec members (i.e. me most of the time) don't have to go back and look at everything that got merged with every release to write them.
- 
- [x ] squash-merge

Added reminder to add changes to wiki and made Markdown file lint-compliant

---

tcf_website/templates/reviews/review.html

- Done
- This PR closes #486.
- Added a [Django template filter](https://docs.djangoproject.com/en/3.1/ref/templates/builtins/#linebreaks) to show the hidden newlines
- Before
- After
- Alternative
1. Write a review containing multiple consecutive newlines
2. Check that it works on the course-instructor page and on the my reviews page.
- The consensus from the meeting was condensing multiple line breaks to one.
|number of newlines | number of reviews|
|:---:|---:|
|any|28687|
|0|26215|
|1|1019|
|2|1416|
|3|29|
|4|1|
|5|2|
|6-8|1|
|9 or more|4|

Show newlines in reviews

---

package-lock.json

- Done
- This PR closes #494 and closes #495, the PRs that were created but `dependabot` but didn't pass the checks due to authentication failure.
- Ran `npm audit fix` to fix packages that require security updates
Not really a screenshot but a copy of my terminal output:
```
$docker exec -ti tcf_django bash
root@a6f6e8beb679:/app# npm i --package-lock-only
audited 179 packages in 4.891s
27 packages are looking for funding
run `npm fund` for details
found 4 vulnerabilities (1 moderate, 3 high)
run `npm audit fix` to fix them, or `npm audit` for details
root@a6f6e8beb679:/app# npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Command Injection …
```

Update package-lock.json for security reasons

---

tcf_website/templates/reviews/review.html
tcf_website/templates/reviews/review_form_content.html

Done
- This PR closes #500 
- Swapped the emoji order of "Recommend" and "Difficulty" so that "Recommend" comes first on both the review page and the review card of a given review.
- Before
- After
- Really not a significant change. Just ensure that the "Recommend" emoji comes before the "Difficulty" emoji in all relevant places (i.e. when writing a new review, the review card for a given course, etc.).
- The two files I changed were the only places I think the emojis appear/there is any order. Let me know if there are other places the emoji order should change too that I missed.
- [] preserve the …

Swap emoji order of recommendability and difficulty

---

tcf_website/views/review.py

Done
Fixes #557 
Refactored the `DeleteReview` view to use Django's `SuccessMessageMixin` for success messages.
Before:
After:
Fixes failing test `test_delete_review_message`.
Incidentally, [my first PR](https://github.com/thecourseforum/theCourseForum2/pull/359) was adding a message for review deletion. At the time, an issue with the `SuccessMessageMixin` meant that it was incompatible with `DeleteView`. At the time your best workaround was to override the `delete` method and add your own messaging logic.
Since then, Django has reimplemented `DeleteView` to use `FormMixin` behind the scenes. This rendered my workaround obsolete, as the obvious way [to implement success messages](https://docs.djangoproject.com/en/4.0/ref/contrib/messages/#django.contrib.messages.views.SuccessMessageMixin) …

Fix #557: deleting reviews does not show message causing test failure

---

tcf_website/templates/browse/browse.html

Done
No issue was created.
Commented out the part of the [browse template](./tcf_website/templates/browse/browse.html) containing the review drive banner.
**Before**
**After**
(I swear, I turned off my adblock for you guys, I have no idea why the ads are blank)
N/A

Remove fall 2021 review drive banner

---

.github/workflows/continuous-integration.yml
.pylintrc
tcf_website/api/filters.py
tcf_website/api/serializers.py
tcf_website/views/discord.py
tcf_website/views/search.py

Pylint is broken on all new builds because `PYTHONPATH` isn't set. Not sure why it isn't being set when it's worked for 2 years, but I'm setting it manually. Also needed to fix a few things to make Pylint compliance back to 10/10.

Fix pylint

---

setup.cfg

- Done
- Currently the [pre-commit hook](https://github.com/thecourseforum/theCourseForum2/blob/be96c761af0d9f5bb2864e2dee7f2d77ee5a833d/precommit.sh#L11) formats with line width 100 which clashes with many formatter defaults. Now format-on-save in most traditional editors will match the actual committed code.
- Create simple `setup.cfg` to configure autopep8 with max-width 100 (instead of the default 80)

match pep8 formatting to pre-commit hook

---

tcf_website/static/blog/blog.css
tcf_website/templates/blog/post.html

- This PR closes #562 
- Edited blog post formatting/rendering
- Before
- After
- Create a post
- There are some things that were listed in the [github md](https://github.com/adamschwartz/github-markdown-kitchen-sink/blob/master/TEST.md) that don't get recognized by markdownify. I don't think this is too big of an issue though because they can be easily recreated by other methods. For example, `- - -` doesn't get recognized, but `* * *` can be used instead. If this is an issue I can try to fix it, but then this evolves beyond a CSS issue.

Blog post rendering

---

README.md

Made some stylistic changes to the README.md
- Before
- After
- *theCourseForum* should be italicized since it is a name. 
- the number of closed issues is not the most relevant thing to a project. 
- `###` should not be used as the headings for a page have a particular meanings for accessibility rather than simply the side of text
- centered things look better
- adding a logo to the top helps with brand recognition 
---
Note: there is already a pull request #679 which I created and @barrett-ruth  commented on. I messed up my commit history and forgot branching (I was being lazy). This PR fixes this with squashed commits and a proper branch.

readme facelift

---

tcf_website/templates/course/course_professor.html

Removed extra quote in tcf_website\templates\course\course_professor.html for review redirect.
(Originally missed when I approved and merged into dev, caught by Barrett).

remove extra quote in review-redirect

---

tcf_website/templates/browse/browse.html
tcf_website/templates/common/qa_form_banner.html
tcf_website/templates/landing/landing.html

- NA
- Added a banner to the landing and browse page that asks for feedback on tCF's questions & answers feature
- Before
- After
- Checked for banner locally
- None

Add QA google form banner

---

Dockerfile
docker-compose.yml

should fix docker now
postgres wasn't fully initialized before migrations were run, causing errors.
used the "wait-for-it" script to ensure it runs first
prod doesn't use docker - no danger there

fix(docker): proper caching + service init

---

.dockerignore

fix windows docker context builds

fix(docker): ignore node_modules to resolve windows builds

---

tcf_core/auth_pipeline.py
tcf_website/views/auth.py

Problem: Whenever someone tried to create an account by email and password (not sign in with Google), clicking on the email verification link would cause a Server 500 Error, and the account would not be created.
The cause of the problem: Between the time the user registers a new account and the time the user clicks on the email verification link, the user's data is stored in the database table `social_auth_partial`. For an unknown reason, the production server behaves as if the verification link was visited BEFORE the user clicks the link. This removes the user's data from the database, such that their account can't be created when they click the link.
Solution: Make the user's data persist in the database until the user manually enters their graduation year, then delete the entry from …

Fix email verification

---

tcf_core/settings/handle_exceptions_middleware.py

- Adding logs to help debug server 500 error
- Reformatted and added request headers to error logs
- Before
> tcf_django  | Error on Load
tcf_django  | Internal Server Error: /department/19/Fall+2024/
tcf_django  | Department matching query does not exist.
tcf_django  | Traceback (most recent call last):
tcf_django  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
tcf_django  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tcf_django  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tcf_django  |   File "/app/tcf_website/views/browse.py", line 57, in department
tcf_django  |     dept = Department.objects.prefetch_related("subdepartment_set").get(pk=dept_id)
tcf_django  | …

Add request headers in error logs

---

tcf_core/settings/handle_exceptions_middleware.py

- Adding logs to help debug server 500 error
- Reformatted and added request headers to error logs
- Before
> tcf_django  | Error on Load
tcf_django  | Internal Server Error: /department/19/Fall+2024/
tcf_django  | Department matching query does not exist.
tcf_django  | Traceback (most recent call last):
tcf_django  |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
tcf_django  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tcf_django  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tcf_django  |   File "/app/tcf_website/views/browse.py", line 57, in department
tcf_django  |     dept = Department.objects.prefetch_related("subdepartment_set").get(pk=dept_id)
tcf_django  | …

Add extra error logs

---

tcf_core/settings/handle_exceptions_middleware.py

Fetch only existing fields from `request.META` Django request objects as it is not guarateed they exist.

fix(middleware): don't fetch DNE fields

---

doc/dev.md
tcf_website/static/course/course_professor.css
tcf_website/static/course/javascript/course_data.js
tcf_website/templates/course/course_professor.html

- This PR closes Issue 652
- Fixed mobile pie chart rendering while retaining existing rendering of charts
- Before
- After
- View pie and bar chart on computer display with varying sizes of screen
- View pie and bar chart on mobile display
- Confirm both are within parameters of the container

Issue 652: Made fixes to pie chart, updated chart.js version

---

tcf_website/models/models.py
tcf_website/views/browse.py

- Created "Default" sorting method for reviews so that only the first ten reviews are fetched when a course instructor is loaded.
- This mode is not selectable and fetches the earliest reviews.

Default sorting option for course - instructor reviews

---

tcf_website/templates/about/current_team.html
tcf_website/views/index.py
tcf_website/views/team_info.json

I separated the marketing and design team on the about page
-
- Before
- 
- After
In order to test, I opened up the about page and then ensured that the people who are on the marketing and design team are not in the same group and rather are split up.
-

fix: seperated marketing and design teams on the about page

---

tcf_core/settings/base.py

Permit CORS for endpoints accessed by `adsbygoogle.js` to have ads on the production site.

Fix Advertisements
