- README.md
- tcf_core/settings.py
- tcf_website/models/models.py
- tcf_website/static/common/rating_card.css
- tcf_website/static/course/course_professor.css
- tcf_website/templates/base/base.html
- tcf_website/templates/common/rating_card.html
- tcf_website/templates/course/course.html
- tcf_website/templates/course/course_professor.html
- tcf_website/templates/department/department.html
- tcf_website/templates/profile/profile.html
- tcf_website/templates/reviews/reviews.html
- tcf_website/tests/test_course.py
- tcf_website/tests/test_instructor.py
- tcf_website/tests/test_utils.py
- tcf_website/views/browse.py
- tcf_website/views/index.py
> Add review aggregation scores.

- precommit
- tcf_core/auth_pipeline.py
- tcf_core/settings.py
- tcf_website/legacy_models.py
- tcf_website/models/models.py
- tcf_website/views/browse.py
- tcf_website/views/index.py
- tcf_website/views/review.py
> Add comments.

- .env.example
- requirements.txt
- tcf_core/settings.py
- tcf_website/management/commands/index_elasticsearch.py
- tcf_website/static/search/search.css
- tcf_website/templates/search/search.html
- tcf_website/urls.py
- tcf_website/views/__init__.py
- tcf_website/views/search.py
* updated comments
* removed excessive commenting
* Working "Instructors" engine
got a another engine working for the Instructor model
* created blank search landing page
* elastic querying works
* response results now format based on engine type
* added id
* simple search results UI
* forgot to add public Dev settings
* removed small detail
* FIXED BUG, wasn't installing 'requests' library
* added mnemonic to indexer & fetcher
elastic app search
* added mnemonic to Course search results + narrowed css scope
* VERY IMPORTANT Elastic clarification
this should be locked in permenantly
* added documentation
* function name clarification
the new name is more representative of what the function actually does
* removed login requirement for search
we will add it back later but want to discuss …
> Search Results from Elastic (#79)

- tcf_website/templates/base/navbar.html
- tcf_website/views/search.py
Just sets the `value` field in the input element of `navbar.html` to {{query}}
> Persists the search query in the search box after searching.

- tcf_website/static/login/login_button.css
- tcf_website/templates/login/login_button.html
I fixed an issue where the login button would go off-center and over the screen when making the window too narrow / zooming in too much. Additionally, I made the login button slightly smaller because it was a little too in-your-face before.
> Login button css fixed!

- tcf_website/static/login/login_button.css
- tcf_website/templates/login/login_button.html
> Perfect Login Button

- .gitignore
Prevents PyCharm settings files from getting pushed to GitHub
> Added .idea folder to gitignore

- requirements.txt
- tcf_core/settings.py
- tcf_core/urls.py
Installed [django-silk](https://github.com/jazzband/django-silk) for performance profiling
#78 is resolved. Originally rolled it into a separate issue (#11 ) but decided to reopen since we're still addressing that.
Created new url at http://localhost:8000/silk/. Can track load time for http requests and db queries as shown here:
> configured django-silk

- tcf_website/static/about/javascript/about.js
- tcf_website/static/common/bind-show-hide.js
- tcf_website/static/common/sorting.js
- tcf_website/static/department/bind-sort.js
- tcf_website/static/reviews/sort_reviews.js
- tcf_website/templates/about/about.html
- tcf_website/templates/common/toolbar.html
- tcf_website/templates/course/course.html
- tcf_website/templates/course/course_professor.html
- tcf_website/templates/department/department.html
- tcf_website/templates/reviews/review.html
- tcf_website/templates/reviews/reviews.html
- tcf_website/templates/reviews/user_reviews.html
I could fix `Uncaught SyntaxError: Unexpected token 'export'` by adding a few `type="module"`s, but somehow the functions needed to be defined beforehand. During the debugging process, I discovered that [using the `onclick` attribute is not a good practice](https://stackoverflow.com/questions/12627443/jquery-click-vs-onclick), so I replaced all of them with `addEventListener`s.
Fix #178 (hopefully?)
This is the screenshot after I've clicked `Rating`, `Difficulty`, `GPA`, `Number`, in that order.
Please squash-merge this one!
> Hot fix for bugs after merging #153

- .eslintignore
- tcf_website/static/reviews/review.js
- tcf_website/templates/course/course_professor.html
- tcf_website/templates/reviews/review.html
- tcf_website/templates/reviews/reviews.html
- tcf_website/templates/reviews/user_reviews.html
Done
Basically reverted PR #211 and fixed the bug that existed at that point with minimal changes
Reverts #211
Notice that there is now a new `id` attribute and no `href`.
> Revert PR#211 vote fix

- tcf_website/templates/landing/landing.html
- tcf_website/views/index.py
Done
- added a modal announcing tcf 2 that appears the first time a user enters the landing page
none rn
> Welcome modal

- tcf_website/static/base/base.css
- tcf_website/static/base/tcf-style.css
- tcf_website/templates/common/toolbar.html
Done
- fixed course sorting button UI bug
- updated common button css
#187 
**Before**
(mobile)
**After**
(mobile)
> Course Sorting Button Styling

- tcf_website/templates/base/sidebar.html
- tcf_website/templates/landing/landing.html
- tcf_website/urls.py
Done
prevent users from accessing review form
> Review form modal

- tcf_website/templates/base/base.html
Done
added google analytics tag
closes #230
> google analytics site tag

- tcf_website/models/models.py
- tcf_website/static/base/tcf-style.css
- tcf_website/templates/instructor/instructor.html
- tcf_website/views/browse.py
> Implemented GPA data on instructor page

- tcf_website/templates/reviews/review.html
Done
Literally commented out 3 lines, idk why I'm making a PR for this
> Comment out review edit button

- tcf_website/templates/base/base.html
- tcf_website/templates/base/sidebar.html
- tcf_website/templates/landing/landing.html
> Add copyright year correctly & dynamically

- tcf_core/settings.py
- tcf_website/urls.py
Done, In progress, etc
- Changed `SOCIAL_AUTH_LOGIN_REDIRECT_URL` to the browse page
- Removed an unnecessary path from `tcf_website/urls.py`
Closes #245
> URL after login

- tcf_website/api/filters.py
- tcf_website/api/views.py
Done
Added a filter that returns only a unique set of `Instructor`s
Fixes #252
Before the fix (count=25):
After the fix (count=9):
> Fix #252 Duplicate data in the Instructor API

- tcf_website/api/views.py
Done
Added `course` and `instructor` parameters to the Semester API
Closes #255
Bloomfield's Introduction to Cybersecurity
> Add course, instructor params to Semester API

- tcf_website/models/models.py
Done
Fixed a typo in the view for my reviews page
Closes #260
before
after
> Hot Fix: "My reviews" page not working

- .travis.yml
- Dockerfile
Done
- Remove unnecessary `cp` in `.travis.yml`
- Replace `npm install {npm packages}` with `npm install` in both `Dockerfile` and `.travis.yml`
- Combine `docker build .` into `docker-compose up` in `Dockerfile`
Closes #287
The build immediately preceding the PR:
The build immediately following the PR:
Hopefully we can save 1.5~2 minutes for every build!
> Refactor build files

- tcf_website/templates/base/navbar.html
- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/notification.html
Done
- Added application banner link in navbar
- Added review drive banner as a dismissable alert on Browse page
> Added team application & review drive banners

- tcf_website/static/course/javascript/course_data.js
- tcf_website/static/course/javascript/instr_data.js
- tcf_website/templates/base/sidebar.html
- tcf_website/templates/course/course_professor.html
- tcf_website/templates/instructor/instructor.html
- tcf_website/views/auth.py
- tcf_website/views/browse.py
> Quickpatch

- .github/workflows/master-to-app-engine.yml
- Done?
- This PR closes none
- Changed master-to-app-engine.yml
- None
- None
- None
> Fix deployment condition

- .github/workflows/master-to-app-engine.yml
- Done
- This PR closes no issues
- Added a missing environment variable
- None
- None
- None
> Add missing environment variable in deployment script

- .config/app.yaml.template
- Done?
- This PR closes no issues
- Added a missing environment variable in app.yaml.template
- None
- None
- None
> Add missing environment variable in app.yaml.template

- tcf_website/templates/base/index.html
- Done (although still working on it)
We're moving forward with a trial of AdSense to get a better idea of our potential revenue. The first step requires verification from Google where they look over the site and verify that this script has been added.
- Added script to `head`
- This is pretty high priority because the code needs to be on prod so that the site can be verified
> Add AdSense script

- tcf_website/templates/base/base.html
- tcf_website/templates/browse/browse.html
- Done
- This PR closes #410 
- The fundraising banner being on *every single page on the site* was a little excessive, so I've put it to just the main browse page.
- Before
- After
N/A
- 
- [ x ] The last reviewer to approve can merge it
> Move fundraising banner to browse only

- tcf_website/static/reviews/review.css
- tcf_website/templates/reviews/review.html
- Done
N/A, this is a hot fix
- See title
- Before
- After
- Review card will be revamped in PR #417 anyway
> Fix spacing bug on review cards

- requirements.txt
- Done
- This PR closes #483.
- Temporarily limited the range of allowed versions for `pylint` in `requirements.txt`
- Before
- After
- Run `docker exec tcf_django pylint --jobs=0 --load-plugins pylint_django --django-settings-module=tcf_core.settings tcf_website tcf_core` on `dev` and on this branch
- Should we run `pip freeze > requirements.txt`
> Temporary fix for broken Pylint 2.8.0

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/review-drive-banner.html
Necessary for review drive, just gonna hit go on this one
> Added review drive banner

- tcf_website/static/reviews/new_review.js
- Done.
- This PR closes #493 
- Simply changed the increments on the progress bar to reflect an encouraged word count of 150 words.
- Ensure that the increments work correctly; They should because I simply changed the numbers and it was working before but make sure just in case.
-N/A
- [] The last reviewer to approve can merge it
- [] preserve the history
- [] squash-merge
> Updated encouraged word count to 150 words

- requirements.txt
- Done
- N/A
- This is a follow-up to #473 (where we fixed the Django version to 3.1.8) and #484 (where we fixed the PyLint version to below 2.8)
- N/A
- Run `docker-compose up` and see if everything works as expected.
- N/A
> Update Django and PyLint

- tcf_website/templates/about/terms.html
- tcf_website/views/index.py
- Done
- N/A
Updated the terms of conditions:
- Added clause to "User Conduct" that users should not name those outside of the faculty listed on the website without explicit consent.
- Revised the date the terms were last reviewed
- Revised the state the laws of the terms apply to (from FL to VA)
- Changed "." to ";" to match the existing pattern
- Looked at it locally.
- Does the wording make sense?
- [] The last reviewer to approve can merge it
- [] preserve the history
- [] squash-merge
> Updated terms conditions

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/review-drive-banner.html
- Done
-Added review drive banner to browse
- Before
- After
-
- [] preserve the history
- [] squash-merge
> Added review banner to browse

- tcf_website/templates/base/sidebar.html
- tcf_website/templates/landing/landing.html
- Done
- This PR closes #563 
- Added blog links that link to /lobg in the homepage, replacing redundant "View Grades" and added it to sidebar with a NEW! marker
- Before
- After
Run PR and look at sidebar and front page
-
> Blog links added to homepage and sidebar

- tcf_website/microsoft-identity-association.json
- tcf_website/urls.py
- tcf_website/views/auth.py
Loads Microsoft verification json: this is necessary in order for Microsoft Azure to ping the given URL and verify tCF for Microsoft auth.
- Done
- N/A (a subset of #308)
- Loads Microsoft verification document in order to be an authorized provider for Microsoft authentication. This is necessary in order for Microsoft Azure to ping the given URL and verify tCF for Microsoft auth. If we aren't verified, UVA blocks the login.
- Before
- After
Check http://127.0.0.1:8000/well-known/microsoft-identity-association.json to make sure the JSON output shows
- After this is merged on the live site, it should verify Microsoft auth even locally? I hope
- Should the …
> Load microsoft verification

- tcf_website/templates/browse/browse.html
- tcf_website/templates/landing/landing.html
- Done
- Removing application banner from site
> Remove application banner

- tcf_website/templates/browse/browse.html
- tcf_website/templates/landing/landing.html
Reverts thecourseforum/theCourseForum2#600
> Revert "Remove application banner"

- package-lock.json
- tcf_website/templates/about/current_team.html
- tcf_website/views/index.py
- tcf_website/views/team_info.json
- Done
- N/A
- Updated team members page to remove old team members
- Verify that the correct profiles show on the team page (don't include new team members yet)
- [] The last reviewer to approve can merge it
- [] preserve the history
> Remove old profiles for f22

- tcf_website/static/reviews/review.js
- Done
- This PR closes #625 
- added a trailing slash to the endpoints
- Before
- After
- upvote a review and reload the page and the vote should remain
- this seems to be a similar issue with #617. I don't know if we want to change the django setting for APPEND_SLASH in a config file somewhere or stay with this fix.
- [] squash-merge
> fixed cant vote issue

- tcf_website/templates/browse/browse.html
- tcf_website/templates/landing/landing.html
- Removed the banner for review drive for Spring 2023 as it is over.
- Before
- After
- See if the banner is gone.
-
> Removed banner from website

- .github/workflows/continuous-integration.yml
- docker-compose.yml
- Manual deployment
- Before
- After
-
> Added manual deployment

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/application_banner.html
- tcf_website/templates/landing/_faqs.json
- tcf_website/templates/landing/landing.html
> Updated and added banner for applications

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/application_banner.html
- tcf_website/templates/landing/_faqs.json
- tcf_website/templates/landing/landing.html
> Added application/interest meeting info

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/application_banner.html
- tcf_website/templates/landing/_faqs.json
- tcf_website/templates/landing/landing.html
Remove application banner
Reverts #667
> Revert "Updated and added banner for applications"

- tcf_website/static/landing/feedbackform.js
- tcf_website/templates/base/sidebar.html
- tcf_website/templates/landing/landing.html
Remove sidebar and don't let forms be submit
@ajnye let me know anything else that needs to be commented out before we revert this later
> ddos: temporarily remove feedback in sidebar

- tcf_website/static/landing/feedbackform.js
- tcf_website/templates/base/sidebar.html
- tcf_website/templates/landing/landing.html
> Remove bug fix form temporaily

- .github/workflows/continuous-integration.yml
> Fix postgres image type

- tcf_core/settings/base.py
- tcf_core/settings/handle_exceptions_middleware.py
> Error Logging

- setup.cfg
mypy support django stubs in linting
> chore(lint): mypy django-stubs plugin

- requirements.txt
- tcf_core/settings/__init__.py
- tcf_core/urls.py
Deprecates Silk.
May need to verify deprecation works on production environment or anything else necessary to remove.
> fix(#755): deprecate and remove silk

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/review-drive-banner.html
- tcf_website/templates/landing/landing.html
Adds the review drive for fall 23.
-
- Before
- After
-
> Added Review Drive Fall 2023 banner

- tcf_website/templates/common/review-drive-banner.html
> fixed review drive banner hashtag

- tcf_website/templates/browse/browse.html
- tcf_website/templates/landing/landing.html
> Removed fall 23 banner

- tcf_website/management/commands/grade_data/csv/2023_spring.csv
> feat(db): 2023 spring semester grades)

- README.md
> fix(readme): use svg link

- .config/.eslintrc.yml
- .githooks/pre-commit
- .github/workflows/continuous-integration.yml
- docker-compose.yml
- package-lock.json
- package.json
- precommit.sh
Reverts thecourseforum/theCourseForum2#791
> Revert "feat(ci): codebase formatting"

- .github/workflows/master-to-app-engine.yml
> fix(gae): update deployment action from deprecated versions to newest versions incorporating Node.js version 20

- tcf_core/auth_pipeline.py
- tcf_core/settings/base.py
Addresses errors in Google App Engine, likely caused by monkey patching in the global scope which become undone by GAE re-importing packages.
- Test email registration in GAE, which is the only environment we've been able to reproduce this error
> Replace global monkey patching

- .github/workflows/master-to-app-engine.yml
> Login fix 2 prod 

- tcf_core/auth_pipeline.py
- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/login-fix-banner.html
- tcf_website/templates/landing/landing.html
- Added banner that indicates login fix.
- Before
- After
-
> Login fix banner

- tcf_core/auth_pipeline.py
- tcf_core/settings/base.py
- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/login-fix-banner.html
- tcf_website/templates/landing/landing.html
- Added login fix banner.
- Before
- After
-
> Login fix banner to prod

- tcf_website/templates/browse/browse.html
- tcf_website/templates/common/review-drive-banner.html
- tcf_website/templates/landing/landing.html
- Added banner for review drive spring 2024
- Before
- After
-
> Added banner for review drive spring 2024

- tcf_website/templates/reviews/review_form_content.html
> fix(review): align progress bar (credit @artiehumphreys)

- pyproject.toml
black and isort configs to match `scripts/format.sh`
> feat: project configs

- scripts/format.bat
- scripts/format.sh
- setup.cfg
update format script to use pyproject settings
> feat: fix formatting configs given pyproject.toml

- tcf_core/settings/base.py
- tcf_website/management/commands/load_review_drive.py
- tcf_website/migrations/0012_alter_review_email.py
- tcf_website/urls.py
> Added checks to make env setting optional

- .config/app.yaml.template
> feat: upgrade python to 3.12

- tcf_website/static/base/bugform.js
Disable the bugform because it is being spammed.
> Disable BugForm

- scripts/reset-db.sh
> fix(docs): add trigram extension

- .github/workflows/continuous-integration.yml
> remove discord in ci file

- tcf_website/templates/base/index.html
Last pr used outdated fontawesome kit, use new one insteda
> Revert Fontawesome kit

- tcf_core/auth_pipeline.py
- tcf_website/tests/test_user.py
- tcf_website/views/browse.py
> Fix full_name proprety

- tcf_website/templates/browse/browse.html
> Second reversion

- .config/app.yaml.template
> fix: python 3.11

- scripts/reset-db.sh
Reste DB wasn't taking in first parameter
> Fix Reset DB Script

- tcf_website/api/views.py
- tcf_website/static/course/javascript/instr_data.js
- tcf_website/static/reviews/new_review.js
> fix(perf): modest page sizes

- tcf_website/management/commands/fetch_data.py
SIS API changed, so we have to update fetch_data.py script. (now also uses pageCount, no longer need to binary search for # of pages)
> Update fetch_data.py script 

- tcf_website/templates/schedule/delete_schedule_modal.html
- tcf_website/templates/schedule/select_schedule_modal.html
> Sb dylan bug fix

- tcf_website/templates/course/course_professor.html
- tcf_website/views/browse.py
##Completed:
- Fix number of reviews displaying the number of ratings including those without text
- Changed 'Comments' header to 'Reviews'
> Fix number of reviews for course instructor

- tcf_core/context_processors.py
- tcf_website/models/models.py
- tcf_website/templates/search/search.html
- tcf_website/templates/search/searchbar.html
- tcf_website/views/search.py
> Enhanced search Bug Fixes

- tcf_website/templates/course/course.html
- tcf_website/templates/course/course_professor.html
- tcf_website/views/browse.py
- edit course.html to display Disciplines in course card (use prerequisites as a template for display)
> add disciplines to course card and cost to section

- tcf_website/views/search.py
> Small filters bug prod push

- tcf_website/views/search.py
> Fixed results returning more than 15 courses

- tcf_website/templates/landing/dashboard.html
- tcf_website/templates/landing/landing.html
- tcf_website/templates/schedule/schedule.html
> add SB on hompage, fix NaN bug on add to schedule

- tcf_website/models/models.py
- fixed time filter not working when no excluded dates are selected
- Before
- After
-
> fixed time filter not working when date is empty

- tcf_website/views/search.py
- limit filter results to 15
- Before
- After
-
> limit filter results to 15

- tcf_website/static/browse/browse.css
- tcf_website/static/department/department.css
- tcf_website/static/icons/icons.css
> dark mode changes to browse and department

- .github/workflows/aws.yml
> feat(aws): update stuff

- .github/workflows/aws.yml
- .github/workflows/ci.yml
> imagine dragons

- requirements.txt
- tcf_core/settings/base.py
collect fast faster staticfiles
> feat(ci): collectfast

- tcf_core/settings/base.py
> aj = off exec

- tcf_core/settings/base.py
> misc: useless change to re-trigger prod workflow

- .github/workflows/aws.yml
> fix(ci): prod is prod

- tcf_core/settings/base.py
make production environment PRODUCTION in ci
> Expose Proper Env

- tcf_core/settings/base.py
> trigger prod ci

- tcf_core/settings/base.py
> fix(ci): revert env for now

- .github/workflows/aws.yml
- tcf_core/settings/base.py
> revert env changes

- tcf_core/settings/base.py
> revert: that was not the fix lol

- tcf_website/templates/schedule/edit_schedule_modal.html
- tcf_website/templates/schedule/schedule_editor.html
- tcf_website/views/schedule.py
- Get the reset button working correctly now
- Before
- After
-
> Fix: fixed reset button issue

- .github/workflows/aws.yml
> fix(ci): use aws rds for prod

- tcf_core/settings/base.py
> fix(ci): also prod db

- tcf_core/settings/prod.py
> fix(login): prod csrf errors

- tcf_core/settings/prod.py
- tcf_website/models/models.py
- tcf_website/templates/department/department.html
- tcf_website/views/browse.py
- Paginated course results on the department page. (e.g. https://thecourseforum.com/department/31/)
- Styling for buttons to navigate between pages.
- Sorted results preserved between pages.
> Paginate department courses

- .github/workflows/aws.yml
- tcf_website/management/commands/load_semester.py
- Temp "To Announced" to load 2025 Fall, Summer; Fix CICD migrations issue
- Before
- After
-
> Temp "To Announced" to load 2025 Fall, Summer; Fix CICD migrations issue

- tcf_website/models/models.py
- tcf_website/templates/department/department.html
- tcf_website/templates/reviews/reviews.html
- added double arrow buttons to navigate to first / last page for review and dept pages
- Before
- After
- played around with the buttons
> Pagination double arrow button
